// 100 Kawaii Frames Data
window.framesData = [
  // === PINK SERIES ===
  { id: 1,  name: "Pink Bunny",      emoji: "🐰", bg: "#FCE4EC", border: "#F48FB1", color: "#E91E63", category: "Pink" },
  { id: 2,  name: "Rose Garden",     emoji: "🌹", bg: "#FFF0F5", border: "#F06292", color: "#E91E63", category: "Pink" },
  { id: 3,  name: "Cherry Blossom",  emoji: "🌸", bg: "#FCE4EC", border: "#EF9A9A", color: "#E57373", category: "Pink" },
  { id: 4,  name: "Candy Pop",       emoji: "🍬", bg: "#FF80AB", border: "#FF4081", color: "#fff",    category: "Pink" },
  { id: 5,  name: "Strawberry",      emoji: "🍓", bg: "#FCE4EC", border: "#EF5350", color: "#C62828", category: "Pink" },
  { id: 6,  name: "Flamingo",        emoji: "🦩", bg: "#F8BBD0", border: "#F48FB1", color: "#880E4F", category: "Pink" },
  { id: 7,  name: "Peach Love",      emoji: "🍑", bg: "#FFCCBC", border: "#FF7043", color: "#BF360C", category: "Pink" },
  { id: 8,  name: "Blush",           emoji: "🌺", bg: "#F8BBD0", border: "#F06292", color: "#880E4F", category: "Pink" },
  { id: 9,  name: "Lollipop",        emoji: "🍭", bg: "#FCE4EC", border: "#EC407A", color: "#880E4F", category: "Pink" },
  { id: 10, name: "Pink Stars",      emoji: "⭐", bg: "#FCE4EC", border: "#F48FB1", color: "#E91E63", category: "Pink" },

  // === PURPLE SERIES ===
  { id: 11, name: "Dreamy Lavender", emoji: "💜", bg: "#EDE7F6", border: "#B39DDB", color: "#6A1B9A", category: "Purple" },
  { id: 12, name: "Galaxy",          emoji: "🌌", bg: "#311B92", border: "#7C4DFF", color: "#EDE7F6", category: "Purple" },
  { id: 13, name: "Wisteria",        emoji: "💐", bg: "#E1BEE7", border: "#CE93D8", color: "#6A1B9A", category: "Purple" },
  { id: 14, name: "Magic Crystal",   emoji: "🔮", bg: "#F3E5F5", border: "#AB47BC", color: "#4A148C", category: "Purple" },
  { id: 15, name: "Plum",            emoji: "🫐", bg: "#E8EAF6", border: "#7986CB", color: "#283593", category: "Purple" },
  { id: 16, name: "Grape Fizz",      emoji: "🍇", bg: "#EDE7F6", border: "#9575CD", color: "#4527A0", category: "Purple" },
  { id: 17, name: "Violet Dream",    emoji: "🌸", bg: "#F3E5F5", border: "#CE93D8", color: "#6A1B9A", category: "Purple" },
  { id: 18, name: "Starlight",       emoji: "✨", bg: "#EDE7F6", border: "#B39DDB", color: "#4527A0", category: "Purple" },
  { id: 19, name: "Fairy Tale",      emoji: "🧚", bg: "#F8F0FF", border: "#CE93D8", color: "#6A1B9A", category: "Purple" },
  { id: 20, name: "Purple Rain",     emoji: "🌂", bg: "#EDE7F6", border: "#7E57C2", color: "#311B92", category: "Purple" },

  // === PASTEL / BABY SERIES ===
  { id: 21, name: "Baby Cloud",      emoji: "☁️", bg: "#E3F2FD", border: "#90CAF9", color: "#1565C0", category: "Pastel" },
  { id: 22, name: "Mint Cream",      emoji: "🍃", bg: "#E8F5E9", border: "#A5D6A7", color: "#1B5E20", category: "Pastel" },
  { id: 23, name: "Cotton Candy",    emoji: "🍬", bg: "#FFF9C4", border: "#FFF176", color: "#F57F17", category: "Pastel" },
  { id: 24, name: "Sky Blue",        emoji: "🦋", bg: "#E0F7FA", border: "#80DEEA", color: "#006064", category: "Pastel" },
  { id: 25, name: "Lemon Drop",      emoji: "🍋", bg: "#FFFDE7", border: "#FFF59D", color: "#F9A825", category: "Pastel" },
  { id: 26, name: "Peach Puff",      emoji: "🍑", bg: "#FFF3E0", border: "#FFCC80", color: "#E65100", category: "Pastel" },
  { id: 27, name: "Lilac Mist",      emoji: "🌷", bg: "#F3E5F5", border: "#CE93D8", color: "#4A148C", category: "Pastel" },
  { id: 28, name: "Rose Quartz",     emoji: "💎", bg: "#FCE4EC", border: "#F48FB1", color: "#880E4F", category: "Pastel" },
  { id: 29, name: "Aqua Glow",       emoji: "🧊", bg: "#E0F2F1", border: "#80CBC4", color: "#004D40", category: "Pastel" },
  { id: 30, name: "Petal Soft",      emoji: "🌼", bg: "#FFFDE7", border: "#FFF176", color: "#F57F17", category: "Pastel" },

  // === ANIMAL SERIES ===
  { id: 31, name: "Choco Bear",      emoji: "🐻", bg: "#EFEBE9", border: "#A1887F", color: "#3E2723", category: "Animal" },
  { id: 32, name: "Sweet Cat",       emoji: "🐱", bg: "#FFF9C4", border: "#FFD54F", color: "#E65100", category: "Animal" },
  { id: 33, name: "Panda Pop",       emoji: "🐼", bg: "#FAFAFA", border: "#BDBDBD", color: "#212121", category: "Animal" },
  { id: 34, name: "Duck Pond",       emoji: "🦆", bg: "#FFFDE7", border: "#FFF176", color: "#F57F17", category: "Animal" },
  { id: 35, name: "Penguin Love",    emoji: "🐧", bg: "#E3F2FD", border: "#90CAF9", color: "#0D47A1", category: "Animal" },
  { id: 36, name: "Fox Autumn",      emoji: "🦊", bg: "#FFF3E0", border: "#FFCC80", color: "#BF360C", category: "Animal" },
  { id: 37, name: "Deer Forest",     emoji: "🦌", bg: "#F1F8E9", border: "#C5E1A5", color: "#1B5E20", category: "Animal" },
  { id: 38, name: "Rainbow Fish",    emoji: "🐟", bg: "#E0F7FA", border: "#80DEEA", color: "#006064", category: "Animal" },
  { id: 39, name: "Bunny Hop",       emoji: "🐇", bg: "#FCE4EC", border: "#F48FB1", color: "#880E4F", category: "Animal" },
  { id: 40, name: "Little Dino",     emoji: "🦕", bg: "#E8F5E9", border: "#A5D6A7", color: "#1B5E20", category: "Animal" },

  // === FOOD / SWEETS SERIES ===
  { id: 41, name: "Sweet Heart",     emoji: "🍰", bg: "#FCE4EC", border: "#F48FB1", color: "#880E4F", category: "Food" },
  { id: 42, name: "Donut Dreams",    emoji: "🍩", bg: "#FFF3E0", border: "#FFCC80", color: "#E65100", category: "Food" },
  { id: 43, name: "Ice Cream",       emoji: "🍦", bg: "#E8EAF6", border: "#9FA8DA", color: "#283593", category: "Food" },
  { id: 44, name: "Waffle Love",     emoji: "🧇", bg: "#FFF8E1", border: "#FFE082", color: "#F57F17", category: "Food" },
  { id: 45, name: "Cake Pop",        emoji: "🍡", bg: "#FCE4EC", border: "#EF9A9A", color: "#B71C1C", category: "Food" },
  { id: 46, name: "Macaron",         emoji: "🧁", bg: "#F8BBD0", border: "#F48FB1", color: "#880E4F", category: "Food" },
  { id: 47, name: "Cookie Jar",      emoji: "🍪", bg: "#FFF8E1", border: "#FFCC02", color: "#795548", category: "Food" },
  { id: 48, name: "Boba Tea",        emoji: "🧋", bg: "#EFEBE9", border: "#A1887F", color: "#3E2723", category: "Food" },
  { id: 49, name: "Cupcake",         emoji: "🧁", bg: "#FCE4EC", border: "#F06292", color: "#880E4F", category: "Food" },
  { id: 50, name: "Candy Rain",      emoji: "🍬", bg: "#E1BEE7", border: "#CE93D8", color: "#4A148C", category: "Food" },

  // === SEASON / NATURE SERIES ===
  { id: 51, name: "Spring Bloom",    emoji: "🌸", bg: "#FCE4EC", border: "#F48FB1", color: "#880E4F", category: "Season" },
  { id: 52, name: "Summer Splash",   emoji: "🌊", bg: "#E0F7FA", border: "#4DD0E1", color: "#006064", category: "Season" },
  { id: 53, name: "Autumn Leaves",   emoji: "🍁", bg: "#FFF3E0", border: "#FF8A65", color: "#BF360C", category: "Season" },
  { id: 54, name: "Winter Snow",     emoji: "❄️", bg: "#E3F2FD", border: "#90CAF9", color: "#0D47A1", category: "Season" },
  { id: 55, name: "Rainbow Arch",    emoji: "🌈", bg: "#FFF9C4", border: "#FFCC02", color: "#F57F17", category: "Season" },
  { id: 56, name: "Sunflower",       emoji: "🌻", bg: "#FFFDE7", border: "#FFF176", color: "#F9A825", category: "Season" },
  { id: 57, name: "Rainy Day",       emoji: "🌧️", bg: "#E8EAF6", border: "#9FA8DA", color: "#283593", category: "Season" },
  { id: 58, name: "Moon Garden",     emoji: "🌙", bg: "#1A1A2E", border: "#7C4DFF", color: "#EDE7F6", category: "Season" },
  { id: 59, name: "Starry Night",    emoji: "🌟", bg: "#0D47A1", border: "#90CAF9", color: "#E3F2FD", category: "Season" },
  { id: 60, name: "Sakura Wind",     emoji: "🌺", bg: "#FCE4EC", border: "#F06292", color: "#880E4F", category: "Season" },

  // === FANTASY SERIES ===
  { id: 61, name: "Mermaid Tale",    emoji: "🧜", bg: "#E0F7FA", border: "#26C6DA", color: "#006064", category: "Fantasy" },
  { id: 62, name: "Unicorn Magic",   emoji: "🦄", bg: "#F3E5F5", border: "#CE93D8", color: "#4A148C", category: "Fantasy" },
  { id: 63, name: "Fairy Wings",     emoji: "🧚", bg: "#F8F0FF", border: "#CE93D8", color: "#6A1B9A", category: "Fantasy" },
  { id: 64, name: "Dragon Egg",      emoji: "🐲", bg: "#E8F5E9", border: "#66BB6A", color: "#1B5E20", category: "Fantasy" },
  { id: 65, name: "Witch Spell",     emoji: "🔮", bg: "#311B92", border: "#7C4DFF", color: "#EDE7F6", category: "Fantasy" },
  { id: 66, name: "Princess Castle", emoji: "🏰", bg: "#FCE4EC", border: "#F48FB1", color: "#880E4F", category: "Fantasy" },
  { id: 67, name: "Magic Wand",      emoji: "🪄", bg: "#E8EAF6", border: "#9FA8DA", color: "#283593", category: "Fantasy" },
  { id: 68, name: "Elf Garden",      emoji: "🌿", bg: "#E8F5E9", border: "#A5D6A7", color: "#1B5E20", category: "Fantasy" },
  { id: 69, name: "Stardust",        emoji: "💫", bg: "#1A1A2E", border: "#CE93D8", color: "#F3E5F5", category: "Fantasy" },
  { id: 70, name: "Angel Halo",      emoji: "😇", bg: "#FFFDE7", border: "#FFD54F", color: "#F57F17", category: "Fantasy" },

  // === RETRO / VINTAGE SERIES ===
  { id: 71, name: "Film Roll",       emoji: "🎞️", bg: "#212121", border: "#FFAB40", color: "#FFF8E1", category: "Retro" },
  { id: 72, name: "Polaroid",        emoji: "📸", bg: "#FAFAFA", border: "#BDBDBD", color: "#212121", category: "Retro" },
  { id: 73, name: "Retro Diner",     emoji: "🎷", bg: "#FCE4EC", border: "#F48FB1", color: "#880E4F", category: "Retro" },
  { id: 74, name: "Cassette Tape",   emoji: "📼", bg: "#263238", border: "#546E7A", color: "#ECEFF1", category: "Retro" },
  { id: 75, name: "Vintage Rose",    emoji: "🌹", bg: "#EFEBE9", border: "#BCAAA4", color: "#4E342E", category: "Retro" },
  { id: 76, name: "Old Postcard",    emoji: "📮", bg: "#FFF8E1", border: "#FFE082", color: "#795548", category: "Retro" },
  { id: 77, name: "Vinyl Record",    emoji: "🎵", bg: "#212121", border: "#9C27B0", color: "#F3E5F5", category: "Retro" },
  { id: 78, name: "80s Neon",        emoji: "🕹️", bg: "#0D0D2B", border: "#FF4081", color: "#FF80AB", category: "Retro" },
  { id: 79, name: "90s Doodle",      emoji: "✏️", bg: "#FAFAFA", border: "#F48FB1", color: "#880E4F", category: "Retro" },
  { id: 80, name: "Film Noir",       emoji: "🎬", bg: "#1C1C1C", border: "#9E9E9E", color: "#FAFAFA", category: "Retro" },

  // === HOLIDAY / SPECIAL ===
  { id: 81, name: "Valentine",       emoji: "💝", bg: "#FCE4EC", border: "#F44336", color: "#B71C1C", category: "Holiday" },
  { id: 82, name: "Christmas",       emoji: "🎄", bg: "#E8F5E9", border: "#F44336", color: "#1B5E20", category: "Holiday" },
  { id: 83, name: "Birthday",        emoji: "🎂", bg: "#FFF9C4", border: "#FFCC02", color: "#F57F17", category: "Holiday" },
  { id: 84, name: "Halloween",       emoji: "🎃", bg: "#1A1A1A", border: "#FF6D00", color: "#FF8F00", category: "Holiday" },
  { id: 85, name: "New Year",        emoji: "🎆", bg: "#0D47A1", border: "#FFD700", color: "#FFFDE7", category: "Holiday" },
  { id: 86, name: "Easter Eggs",     emoji: "🥚", bg: "#F3E5F5", border: "#CE93D8", color: "#4A148C", category: "Holiday" },
  { id: 87, name: "Summer Festival", emoji: "🎉", bg: "#FFF3E0", border: "#FF8A65", color: "#BF360C", category: "Holiday" },
  { id: 88, name: "Wedding Day",     emoji: "💍", bg: "#FAFAFA", border: "#F8BBD0", color: "#880E4F", category: "Holiday" },
  { id: 89, name: "Graduation",      emoji: "🎓", bg: "#E8EAF6", border: "#7986CB", color: "#1A237E", category: "Holiday" },
  { id: 90, name: "Fireworks",       emoji: "🎇", bg: "#0A0A2A", border: "#FF4081", color: "#fff",    category: "Holiday" },

  // === AESTHETIC / TRENDY ===
  { id: 91, name: "Y2K Glam",        emoji: "💿", bg: "#E0F7FA", border: "#00BCD4", color: "#006064", category: "Aesthetic" },
  { id: 92, name: "Cottagecore",     emoji: "🍄", bg: "#F1F8E9", border: "#8BC34A", color: "#33691E", category: "Aesthetic" },
  { id: 93, name: "Dark Academia",   emoji: "📚", bg: "#2C1810", border: "#8D6E63", color: "#D7CCC8", category: "Aesthetic" },
  { id: 94, name: "Light Academia",  emoji: "🕯️", bg: "#FFF8E1", border: "#D7CCC8", color: "#4E342E", category: "Aesthetic" },
  { id: 95, name: "Vaporwave",       emoji: "🌴", bg: "#1A1A2E", border: "#FF4081", color: "#E040FB", category: "Aesthetic" },
  { id: 96, name: "E-Girl",          emoji: "🖤", bg: "#212121", border: "#E91E63", color: "#F8BBD0", category: "Aesthetic" },
  { id: 97, name: "Coquette",        emoji: "🎀", bg: "#FCE4EC", border: "#F48FB1", color: "#880E4F", category: "Aesthetic" },
  { id: 98, name: "Soft Girl",       emoji: "🌸", bg: "#FFF0F5", border: "#F48FB1", color: "#E91E63", category: "Aesthetic" },
  { id: 99, name: "Indie Kid",       emoji: "🌻", bg: "#FFFDE7", border: "#FFF176", color: "#827717", category: "Aesthetic" },
  { id:100, name: "Angel Aesthetic", emoji: "🤍", bg: "#FAFAFA", border: "#E1BEE7", color: "#6A1B9A", category: "Aesthetic" },
];